import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider"
import { authOptions } from "./api/auth/[...nextauth]/route";


const CBR = localFont({
  src: "./fonts/CBR.woff",
  variable: "--font-CBR",
  weight: "100 900",
});
const CBB = localFont({
  src: "./fonts/CBB.woff",
  variable: "--font-CBB",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${CBR.variable} ${CBB.variable} antialiased`}>
        <SessionProvider session={session}>
        <Navbar/>
        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
